version: '3.1'
services:
  db-postgres:
    image: "cucumberpostgresimage"
    container_name: "cucumberpostgresinstance"
    environment:
      POSTGRES_USER: "devuser"
      POSTGRES_PASSWORD: "dev&USER@."
      POSTGRES_DB: "piratedb"
    build: docker-postgres
    ports:
      - 9900:5432
    restart: always
    stdin_open: true
    tty: true
    logging:
      options:
        max-size: "10m"
        max-file: "10"